"""
Minimal Nav2 stack for the Nav2 validation experiment.

Only three things run, because only three are needed:

  loopback_simulator   the plant: integrates cmd_vel at update_duration = 0.01 s
                       (verified in the installed package), publishes odom + TF
  controller_server    hosts RegulatedPurePursuitController AND serves the
                       /follow_path action directly -- so no planner, no BT
                       navigator, no map server (the local costmap is configured
                       with no layers, see make_params.py)
  letg2_delay_node     the injected delay, cmd_vel_nav -> cmd_vel

DELIBERATELY ABSENT: velocity_smoother.  The stock navigation_launch starts one,
and it would add an unmeasured lag to tau_tot (plan v2 §2.2).  Here the delay node
occupies that slot instead, which is also why the wiring is unambiguous:

    controller_server --cmd_vel_nav--> delay node --cmd_vel--> loopback_simulator

Args:
  params_file   generated by make_params.py for the current sweep point
  delay_sec     tau to inject
"""
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, OpaqueFunction
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def plant_node(context, *args, **kwargs):
    """Build the plant node with a parameter set that matches the chosen build.

    actuator_tau is a term of Theorem 2 (the first moment of a first-order
    actuator lag), but it exists only in loopback_actuator.  Handing it to the
    shipped node would abort that node with an undeclared-parameter error, so the
    decision has to be made after sim_exe is resolved -- hence OpaqueFunction.
    """
    sim_exe = LaunchConfiguration('sim_exe').perform(context)
    params = {
        'update_duration': float(LaunchConfiguration('update_duration')
                                 .perform(context)),
        'publish_clock': False,      # wall clock everywhere
        'scan_publish_dur': 1.0e6,   # no scan: nothing consumes it
        'base_frame_id': 'base_link',
        'publish_map_odom_tf': True,
        'use_sim_time': False,
    }
    if sim_exe == 'loopback_actuator':
        params['actuator_tau'] = float(LaunchConfiguration('actuator_tau')
                                       .perform(context))
    if sim_exe == 'loopback_bicycle':
        params['wheelbase'] = float(LaunchConfiguration('wheelbase')
                                    .perform(context))
        params['max_steer'] = float(LaunchConfiguration('max_steer')
                                    .perform(context))
    return [Node(
        package=LaunchConfiguration('sim_pkg'),
        executable=sim_exe,
        name='loopback_simulator',
        output='screen',
        parameters=[params],
    )]


def generate_launch_description():
    params_file = LaunchConfiguration('params_file')
    delay_sec = LaunchConfiguration('delay_sec')

    return LaunchDescription([
        DeclareLaunchArgument('sim_pkg', default_value='nav2_loopback_sim',
                              description='package providing the plant node'),
        DeclareLaunchArgument('sim_exe', default_value='loopback_simulator',
                              description="'loopback_midpoint' (midpoint-heading "
                                          "diagnostic) or 'loopback_actuator' "
                                          '(first-order actuator lag)'),
        DeclareLaunchArgument('params_file'),
        DeclareLaunchArgument('delay_sec', default_value='1.0'),
        # update_duration is the plant's own ZOH; it contributes T_sim/2 to tau_tot.
        # Exposed as a launch argument because it is a TERM OF THEOREM 2 in its own
        # right, not a fixed implementation detail -- sweeping it tests that term
        # directly, the way the reference engine swept its smoothing constant.
        # The simulator reads it once, to build its timer, so it cannot be set
        # dynamically: each value needs its own launch.
        DeclareLaunchArgument('update_duration', default_value='0.01'),
        # actuator_tau is the time constant of a first-order lag applied to
        # cmd_vel inside the plant, i.e. the ONE omitted physical term in an
        # otherwise ideal integrator.  Its impulse response has first moment
        # exactly T, so Theorem 2 predicts tau_tot gains T with coefficient 1.
        # Only loopback_actuator declares it; 0 reproduces the shipped plant.
        DeclareLaunchArgument('actuator_tau', default_value='0.0'),
        # Ackermann steering bound.  kappa_max = tan(max_steer)/wheelbase;
        # max_steer = 0 disables it and the node is the shipped plant.
        DeclareLaunchArgument('wheelbase', default_value='0.5'),
        DeclareLaunchArgument('max_steer', default_value='0.0'),

        OpaqueFunction(function=plant_node),

        # The loopback simulator looks up base_link->base_scan for its fake laser.
        # Nothing consumes /scan here (the local costmap has only an inflation
        # layer), but without this transform it logs a lookup failure every cycle.
        Node(
            package='tf2_ros',
            executable='static_transform_publisher',
            name='base_link_to_base_scan',
            output='log',
            arguments=['0', '0', '0.1', '0', '0', '0', 'base_link', 'base_scan'],
        ),

        Node(
            package='nav2_controller',
            executable='controller_server',
            name='controller_server',
            output='screen',
            parameters=[params_file, {'use_sim_time': False}],
            remappings=[('cmd_vel', 'cmd_vel_nav')],
        ),

        Node(
            package='letg2_nav2_validation',
            executable='delay_node',
            name='letg2_delay_node',
            output='screen',
            parameters=[{
                'delay_sec': delay_sec,
                'release_rate_hz': 500.0,
                'input_topic': 'cmd_vel_nav',
                'output_topic': 'cmd_vel',
                'use_sim_time': False,
            }],
        ),

        Node(
            package='nav2_lifecycle_manager',
            executable='lifecycle_manager',
            name='lifecycle_manager_letg2',
            output='screen',
            parameters=[{
                'autostart': True,
                'node_names': ['controller_server'],
                'use_sim_time': False,
            }],
        ),
    ])
